---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - name: 'http'
    port: 80
    targetPort: 8080
  selector:
    app: nginx
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: TZ
          value: "Europe/Zurich"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
          - name: var-run
            mountPath: /var/run
          - name: var-cache-nginx
            mountPath: /var/cache/nginx
          - name: var-log-nginx
            mountPath: /var/log/nginx
          - name: static
            mountPath: /static
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
      - name: filebeat
        image: docker-registry.default.svc:5000/test-invenio/filebeat
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        # - name: ELASTICSEARCH_HOST
        #   value: elasticsearch
        # - name: ELASTICSEARCH_PORT
        #   value: "9200"
        # - name: ELASTICSEARCH_USERNAME
        #   value: elastic
        # - name: ELASTICSEARCH_PASSWORD
        #   value: changeme
        # - name: ELASTIC_CLOUD_ID
        #   value:
        # - name: ELASTIC_CLOUD_AUTH
        #   value:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: var-log-nginx
          mountPath: /var/log/nginx
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: var-run
        emptyDir: {}
      - name: var-cache-nginx
        emptyDir: {}
      - name: var-log-nginx
        emptyDir: {}
      - name: static
        emptyDir: {}