host: inveniordm.web.cern.ch

haproxy:
  inside_cluster: true
  maxconn: 100

nginx:
  max_conns: 100
  replicas: 2

web:
  image: inveniosoftware/rdm-sandbox
  replicas: 6
  uwsgi:
    processes: 6
    threads: 4
  autoscaler:
    enabled: false
    # Scale when CPU usage gets to
    scaler_cpu_utilization: 65
    max_web_replicas: 10
    min_web_replicas: 2


worker:
  enabled: true
  image: inveniosoftware/rdm-sandbox
  # Invenio Celery worker application
  app: invenio_app.celery
  # Number of concurrent Celery workers per pod
  concurrency: 2
  log_level: INFO
  replicas: 2

redis:
  inside_cluster: true

rabbitmq:
  inside_cluster: true

postgresql:
  inside_cluster: false

elasticsearch:
  inside_cluster: false
